-- 既存の授業画面も保持。新しいアプリのテーブルは points / point_photos の2つ。
CREATE TABLE enshu_items (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 title varchar(255), genre varchar(255), platform varchar(255), status varchar(255),
 created_at timestamp, updated_at timestamp
);
CREATE TABLE kadai_items (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 title varchar(255), genre varchar(255), platform varchar(255), status varchar(255),
 created_at timestamp, updated_at timestamp
);
CREATE TABLE points (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 request_id uuid NOT NULL UNIQUE,
 title varchar(100) NOT NULL CHECK (length(trim(title)) > 0),
 latitude double precision NOT NULL CHECK (latitude BETWEEN -90 AND 90),
 longitude double precision NOT NULL CHECK (longitude BETWEEN -180 AND 180),
 municipality varchar(100), memo varchar(1000) NOT NULL DEFAULT '',
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX points_updated_at_idx ON points (updated_at DESC, id DESC);
CREATE TABLE point_photos (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 point_id bigint NOT NULL REFERENCES points(id) ON DELETE CASCADE,
 image_data bytea NOT NULL, content_type varchar(30) NOT NULL,
 sort_order integer NOT NULL CHECK (sort_order BETWEEN 0 AND 2),
 UNIQUE(point_id, sort_order)
);
