CREATE TABLE app_users (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 username varchar(40) NOT NULL UNIQUE,
 password_hash varchar(100) NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now()
);
-- 旧データは所有者不明として保持し、登録した人へ自動で割り当てない。
ALTER TABLE points ADD COLUMN owner_id bigint REFERENCES app_users(id);
CREATE INDEX points_owner_idx ON points(owner_id,updated_at DESC);
CREATE TABLE point_history (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 owner_id bigint NOT NULL REFERENCES app_users(id),
 point_id bigint NOT NULL,
 action varchar(10) NOT NULL,
 title varchar(100) NOT NULL,
 snapshot jsonb,
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX history_owner_idx ON point_history(owner_id,id DESC);
